### ISSUE TITLE
Unable get open mod menu 

### ISSUE THREAD

**Issue by PrabhakarManara** [SchuhBaum/SimplifiedMoveset#10]
I installed your mod and activated it in the remix menu( had to restart the game to complete installation). Now when i double click on SimplifiedMoveset in remix mod menu, it say no menu available for this mod. I tried to play spearmaster campaign and found no change in beam climbing or anything. what am i missing?

**Comment by SchuhBaum** [comment]
This is a common issue (for all mods). Disable and enable all mods (you need to restart twice). If that does not help then check out the Section FAQ for other fixes.

**Comment by PrabhakarManara** [comment]
I disabled all mods and enabled them couple of times now, restarted thrice. 

when I restarted, one time I got the prompt saying "mods are changed and needs to update something", I clicked continue. It finished updating something. But still, double clicking on SimpliedMoveset in the remix menu says, this mod doesnt have remix ui. 

My RW version is 1.9.15 and SimplifiedMoveset version is 2.5.3

**Comment by SchuhBaum** [comment]
There are other fixes. But these are some old files did not get updated correctly (RW v1.5 -> v1.9+). I assume that is not the case for you. If you are on Steam Deck or Linux there are specific things you have to do to use mods there.

You can try to disable all mods and only enable this one.
When you have to click continue then a mod got updated (Steam downloaded an update). This can also trigger the bug again. The problem is that the game can mess up the loading of mods. (If a mods fails to load for any reason it stops loading further mods.) The option menu is just a symptom. These mods are not loaded.

**Comment by PrabhakarManara** [comment]
I disabled all other mods and kept only this, but the problem still remains. 

I am on Linux

**Comment by SchuhBaum** [comment]
Check the FAQ and maybe the Rain World Discord server. Mods don't work on Linux by default. In the FAQ I posted a solution that someone posted in the comment section.

**Comment by PrabhakarManara** [comment]
I added `winhttp` in the library section of winecfg, that solved it.

**Comment by SchuhBaum** [comment]
Nice!
